apiVersion: v1
kind: Secret
metadata:
  name: webhook-enricher-secret
  namespace: analytics
type: Opaque
stringData:
  token: "607258b0bd5b3bb6029cc2bb791b72a63b39386cf10b69a50e19e253275a1e7b"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuma-webhook-enricher
  namespace: analytics
  annotations:
    # TODO: Reativar com IP correto da VM após descobrir o IP real de saída
    # nginx.ingress.kubernetes.io/whitelist-source-range: "212.115.125.21/32"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /webhook
        pathType: Prefix
        backend:
          service:
            name: kuma-webhook-enricher
            port:
              number: 80
